version: "3.9"

services:
    app-db:
        image: postgres:15-alpine
        container_name: cstt_app_db
        restart: always
        environment:
            POSTGRES_USER: twinhter
            POSTGRES_PASSWORD: "@Twin24"
            POSTGRES_DB: cstt_db
        ports:
            - "5432:5432"
        volumes:
            - cstt_postgres_data:/var/lib/postgresql/data

    ai-db:
        image: postgres:15-alpine
        container_name: cstt_ai_db
        restart: always
        environment:
            POSTGRES_USER: ai_user
            POSTGRES_PASSWORD: ai_pass
            POSTGRES_DB: ai_kb_db
        ports:
            - "5433:5432"
        volumes:
            - ai_postgres_data:/var/lib/postgresql/data

volumes:
    cstt_postgres_data:
        external: true
    ai_postgres_data:
